name: Deploy Server
on:
  push:
    branches:
      - main
    paths:
      - server/**

env:
  NOTION_OAUTH_SECRET: ${{secrets.NOTION_OAUTH_SECRET}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Setup Node v16
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Setup Rust Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Install dependencies
      working-directory: ./server
      run: npm install --prefix ./

    - name: Run build
      working-directory: ./server
      run: npm run build

    - name: Running tests
      working-directory: ./server
      run: npm test

    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: mintlify-connect-server
        team: mintlify
        heroku_email: han@mintlify.com
        appdir: server